# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: creat venv
    init: python3 -m venv env
  - name: activate venv
    init: source env/bin/activate
  - name: Install requirements
    init: pip install -r requirements.txt
vscode:
    extensions:
        - ms-toolsai.jupyter
