# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - init: >  
	python3 -m venv env
	source env/bin/activate
      command: >
	python3 -m venv env
	source env/bin/activate
    - init: >
          gp open README.md;
          pip install -r "requirements.txt";
      command: >
          gp open README.md;
          pip install -r "requirements.txt";
vscode:
    extensions:
        - ms-toolsai.jupyter
